/**
 * Generates src/data/us-map.ts from the public-domain us-atlas state
 * boundaries (US Census Bureau cartographic files).
 *
 *   npm run build:map
 *
 * This is the only step that needs network access; the generated file is
 * committed, so `npm run dev`, `npm test` and `npm run build` stay offline.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { geoAlbersUsa, geoPath } from "d3-geo";
import { feature } from "topojson-client";

const SOURCE = "https://cdn.jsdelivr.net/npm/us-atlas@3.0.1/states-10m.json";
const OUT = new URL("../src/data/us-map.ts", import.meta.url);

// The d3 convention for geoAlbersUsa: a 975x610 viewport at scale 1300.
const WIDTH = 975;
const HEIGHT = 610;
const PRECISION = 1;

/** A geoPath context that rounds as it writes, instead of emitting full floats. */
function roundingContext(digits) {
  let out = "";
  const n = (value) => {
    let text = value.toFixed(digits);
    // Trim only the fractional tail, so "10.0" becomes "10" and not "1".
    if (text.includes(".")) text = text.replace(/\.?0+$/, "");
    return text === "-0" ? "0" : text;
  };
  return {
    toString: () => out,
    reset() {
      out = "";
    },
    moveTo(x, y) {
      out += `M${n(x)},${n(y)}`;
    },
    lineTo(x, y) {
      out += `L${n(x)},${n(y)}`;
    },
    closePath() {
      out += "Z";
    },
    arc() {
      throw new Error("arc() is only used for point geometry, which we do not render");
    },
  };
}

const usStates = JSON.parse(
  readFileSync(new URL("../src/data/us-states.json", import.meta.url), "utf-8"),
);
const byName = new Map(usStates.map(([state, , code]) => [state, code]));

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`${SOURCE} -> HTTP ${response.status}`);
const topology = await response.json();

const projection = geoAlbersUsa()
  .scale(1300)
  .translate([WIDTH / 2, HEIGHT / 2]);
const context = roundingContext(PRECISION);
const path = geoPath(projection, context);
const measure = geoPath(projection);

const paths = [];
const kept = [];
const seen = new Set();
for (const state of feature(topology, topology.objects.states).features) {
  const code = byName.get(state.properties.name);
  // Territories and DC are in the source but not in the deck.
  if (code === undefined) continue;

  kept.push(state);
  context.reset();
  path(state);
  const d = context.toString();
  if (d === "") throw new Error(`${state.properties.name} projected to an empty path`);

  seen.add(code);
  paths.push([code.toLowerCase(), d]);
}

const missing = usStates.map(([, , code]) => code).filter((code) => !seen.has(code));
if (missing.length > 0) throw new Error(`No geometry for: ${missing.join(", ")}`);

paths.sort(([a], [b]) => a.localeCompare(b));

// Frame the viewBox on what actually got drawn. The stock d3 975x610 frame
// clips Alaska's western Aleutians, and clipping the state being quizzed is
// exactly the thing this map exists to avoid.
const PAD = 8;
const [[x0, y0], [x1, y1]] = measure.bounds({ type: "FeatureCollection", features: kept });
const round = (value) => Math.round(value * 10) / 10;
const viewBox = [
  round(x0 - PAD),
  round(y0 - PAD),
  round(x1 - x0 + PAD * 2),
  round(y1 - y0 + PAD * 2),
].join(" ");

const body = paths.map(([id, d]) => `  ${id}: ${JSON.stringify(d)},`).join("\n");
writeFileSync(
  OUT,
  `// Generated by scripts/build-map.mjs from ${SOURCE} -- do not edit by hand.
// Albers USA projection (Alaska and Hawaii inset), framed on the drawn bounds.

export const MAP_VIEWBOX = "${viewBox}";

/** Card id (lowercased postal code) -> SVG path data. */
export const STATE_PATHS: Record<string, string> = {
${body}
};
`,
  "utf-8",
);

const bytes = paths.reduce((sum, [, d]) => sum + d.length, 0);
console.log(`Wrote ${paths.length} states, ${(bytes / 1024).toFixed(1)} kB of path data`);
